# Generated by Django 4.1.2 on 2022-10-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clientes",
            fields=[
                ("id_cliente", models.AutoField(primary_key=True, serialize=False)),
                ("cedula_cliente", models.IntegerField(max_length=50)),
                ("nombre_cliente", models.CharField(max_length=50)),
                ("apellidos_cliente", models.CharField(max_length=50)),
                ("direccion_cliente", models.CharField(max_length=100)),
                ("ciudad_cliente", models.CharField(max_length=50)),
                ("pais_cliente", models.CharField(max_length=50)),
                ("telefono_cliente", models.IntegerField(max_length=50)),
                ("email_cliente", models.CharField(max_length=50)),
            ],
        ),
    ]
