# Generated by Django 3.0 on 2022-10-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_clientes_cedula_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrar',
            fields=[
                ('cedula', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='id_cliente',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cedula_cliente',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefono_cliente',
            field=models.CharField(max_length=30),
        ),
    ]
